# Generated by Django 6.1 on 2026-08-25 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoEstudantil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('aluno_responsavel', models.CharField(max_length=100)),
                ('turma', models.CharField(max_length=50)),
                ('investimento_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('custo_fixo_mensal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('custo_variavel_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margem_lucro_desejada', models.DecimalField(decimal_places=2, max_digits=5)),
                ('aliquota_imposto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='gestao.projetoestudantil')),
            ],
        ),
        migrations.CreateModel(
            name='SimulacaoViabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projecao_vendas_mensal', models.IntegerField()),
                ('preco_venda_calculado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ponto_equilibrio_unidades', models.IntegerField(blank=True, null=True)),
                ('payback_meses', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.projetoestudantil')),
            ],
        ),
    ]
